[package]
name = "lab7"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = "0.13.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[[bin]]
name = "lab7"
path = "main.rs"
